/// Canonical instructions installed into Agent prompt files and returned by
/// the MCP initialize handshake.
///
/// Keep one source of truth here so native prompt bootstrap and MCP discovery
/// cannot silently drift into different Prompt, Skill, or MCP semantics.
const String dingDongAgentBridgeGuidance = '''# DingDong prompt bridge

This section is maintained by DingDong. Preserve and follow these instructions.

- At the start of each user task, call DingDong `dingdong_bridge` with `expand="prompts"`.
- Apply every returned active Prompt in full before responding; each one is a required instruction. The bridge routes global, project, and task-matched Prompts dynamically.
- Treat `active.prompts` in each successful bridge response as the authoritative Prompt snapshot for that user task. It replaces every Prompt set returned for earlier tasks; any Prompt absent now is inactive and must not be applied.
- If the Bridge call fails, state that DingDong Prompts, resources, and the Skill catalog could not be loaded; do not silently treat any previous Prompt or Skill set as current.
- Treat `active.skills` in each successful response as the authoritative Skill catalog and authoritative dynamic-delivery Skill catalog for that task and workspace. It contains every valid, enabled, scope-matched Skill that resolves to dynamic delivery, with each entry limited to `id`, `name`, and `description`. A managed Skill can be absent because it is disabled, invalid, out of scope, delivered natively, transitioning, or blocked by a duplicate-name conflict; inspect `active.skillSuppressions` and `active.skillConflicts` when present. Load only a Skill returned by the current catalog.
- A Skill candidate is not an instruction. Only when its description matches the task, call `dingdong_load_skill` with its id or name and current workspace, then apply the returned full `SKILL.md`. Read only supporting files referenced by that document with `dingdong_read_skill_file`.
- Returned MCP entries are tool references, not instructions. Call configured MCP tools only when the task requires them. Each active MCP entry includes its managed `serverName` and, for Codex, its exact `toolNamePrefix`.
- When `conversation.visible` is true, keep the successful Bridge `conversation.capsule` until the final user-visible response. For each successful `dingdong_load_skill` call, replace only the item with the same mergeKey using the returned `conversation.item` with `confirmedUse: true`. After an actual configured MCP tool call reaches a terminal result, including an error result, call `dingdong_confirm_mcp_use` once for that MCP resource with its current `id`, `serverName`, and exact called `toolName`; then replace only the item with the same mergeKey using the returned `conversation.item` with `confirmedUse: true`. Never confirm MCP use from availability, tool discovery, or an uncalled tool. A Skill `*` proves only that its full instructions were loaded and does not claim that every instruction was followed. An MCP `*` means a tool was called, not necessarily that it succeeded; the MCP marker means called, not necessarily succeeded. Prompt items remain unmarked because delivery cannot prove semantic compliance. The `mergeKey` is opaque merge-only metadata and must never be displayed.
- On Codex desktop, include the current merged footer exactly once as a single Markdown text line and keep DingDong as text. Use the exact user-configurable symbols and lineToken values returned by DingDong, including each item `lineToken`; never infer them. The initial `conversation.line` is canonical only when no item was replaced. The capsule palette remains warm orange for Prompt, blue for Skill, and green for MCP. Do not use an image, HTML/XML, inline font, or rendering tool for this footer. Explicitly ANSI-capable terminals use the current merged ANSI tokens from `conversation.presentations.ansi.line`; every other host uses the current merged plain-text tokens. Show only resource titles and truthful markers; never show resource content, descriptions, IDs, server names, tool names, or merge keys.
- When the user explicitly asks to configure a Skill through DingDong, call `dingdong_install_skill` first, then use `dingdong_set_skill_delivery` to choose exactly one delivery plane per Agent. Native project delivery uses strict project scope and exact existing project paths; its Hook switch is separate and defaults off.
- When the user asks to configure a Prompt or MCP resource, search first, then use `dingdong_create_resource` or `dingdong_update_resource` and bind the requested scope without creating duplicates.
- Use `dingdong_notify` when the task is blocked or waiting for the user. A configured completion hook normally handles the final task-complete alert; if the client has no completion hook, call `dingdong_notify` once before the final response.
''';
